### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by cgasb** [MLlab4CS/DeepGLSTM#1]
Good morning, 
I am trying to test DeepGLSTM on my own data. I successfully installed all the requirements as specified in the requirements.txt file, but when I launch the data_creation.py script I received this error: 

Traceback (most recent call last):
  File "data_creation.py", line 9, in <module>
    from utils import *
  File "/content/drive/MyDrive/DeepGLSTM-main/utils.py", line 5, in <module>
    from torch_geometric.data import InMemoryDataset
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/__init__.py", line 7, in <module>
    import torch_geometric.data
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/usr/local/lib/python3.7/dist-packages/torch_sparse/__init__.py", line 16, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
  File "/usr/local/lib/python3.7/dist-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.7/dist-packages/torch_sparse/_convert_cpu.so: undefined symbol: _ZN2at4_ops5zero_4callERNS_6TensorE

This happens both on my local device (with no GPU) and on a google colab. Could it be a problem with the version of torch sparse? 
Thank you in advance,
Chiara

**Comment by MLlab4CS** [comment]
Hi Chiara,
I think the issue is related to version mismatch of the required packages. First of all ensure that you have installed the torch version 1.9.0  and also send me the version of all the required packages which you are installing from requirements.txt. If issue still persists can you please attach one snap of your dataset / demo dataset.
